### ISSUE TITLE
 how to get client ip?

### ISSUE THREAD

**Issue by cqu1980** [ClusterWS/ClusterWS#100]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

### Details
I want to know how to get client ip?

**Comment by goriunov** [comment]
In 3.1.3 you can access remote address with the code above.

**Comment by caracal7** [comment]
`req.remoteAddress` not worked in 4.0.x

**Comment by goriunov** [comment]
@caracal7 remote address has been moved to better align with specifications in version 4 but has not yet been exposed correctly you can access this data through 

```js
socket.socket._socket.remoteAddress;

// later will be moved in to 
socket._socket.remoteAddress
```

**Comment by caracal7** [comment]
@goriunov  Thanks a lot)
