### ISSUE TITLE
uws no longer being published

### ISSUE THREAD

**Issue by andressuy** [ClusterWS/ClusterWS#101]
### Submitting

- [x] Bug
- [ ] Question
- [ ] Suggetion
- [ ] Other

### Details

https://www.npmjs.com/package/uws

As you can see, 17hs ago the package uws went the way of the dodo, now if you try lo install the package you get nothing except a README.md with "I no longer publish to NPM. Find me elsewhere."

FAST FIX: replace dependency "uws": "ˆ10.148.0" for "uws": "10.148.1"

**Comment by Crypto-Q** [comment]
As stated above use the following to install:

`npm i uws@10.148.1`

I have emailed the author to see if he is making it available again publicly on a different platform instead of NPM.

**Comment by goriunov** [comment]
I have updated dependency for `uws` and deployed new version 3.1.3 should be working fine from now.
