### ISSUE TITLE
Add onUnsubscribe, channelClose, onRecieve middleware

### ISSUE THREAD

**Issue by Crypto-Q** [ClusterWS/ClusterWS#103]
### Submitting

- [ ] Bug
- [x] Question
- [x] Suggetion
- [ ] Other

### Details
Do you have any plans to include additional middleware listeners, for example:
- **unSubscribe** function
- **channelClose** function
- **onRecieve** function

**Unsubscribe Use Case**
Upon a authenticated client subscribing to a channel, my worker will consume a RabbitMQ queue. When a particular client unsubscribes because the they changed the view in the web app, I would like to be able to hook in and stop consuming the appropriate queue.

**channelClose Use Case**
Upon a client subscribing to a channel, my worker will consume a RabbitMQ queue. When the channel is closed or the number of subscribers is 0 I would like to be able to hook in and stop consuming the appropriate queue.

**onRecieve Use Case**
Upon a client submitting data to the server, intercept requests and perform basic some basic/global security checks and functions (strip certain characters before processing).

**Comment by goriunov** [comment]
That is really good suggestions, i have not thought about it, seems to be very useful. I will add it to the next release.

**Comment by Crypto-Q** [comment]
Thanks it will be really helpful. Great project by the way. SC done the right way with typescript.

At the minute I can consume a queue from within a worker using the 'onSubscribe' middleware and keep a track of the number of subscribers. When this reaches 0 I would like to be able to stop consuming from my queue.

![applicationframehost_2018-08-07_19-16-24](https://user-images.githubusercontent.com/14010926/43794611-bfc23ade-9a76-11e8-8e1b-4eaeee9b01cd.png)

**Comment by goriunov** [comment]
Currently working on implementing your suggestions (hopefully will deploy new version by the end of the week) :)

**Comment by goriunov** [comment]
I have release 3.2.0 which adds above functionality (with slightly different namings) check [wiki](https://github.com/ClusterWS/ClusterWS/wiki/Middleware-Functions) and [Release notes](https://github.com/ClusterWS/ClusterWS/releases) for more information.

**Comment by goriunov** [comment]
PS: Current documentation is written not in the best way (there are plans on update all documentation with more example  and moving it out of wiki) it requires alot of time and i hope i will be able to rewrite everything by version 4.0.0 release.

**Comment by Crypto-Q** [comment]
Massive thanks for implementing this so quickly. Really useful features.

I am also snowed in with code to write but if I get some free time I will try and write a paragraph for each middleware that explains it as precisely as possible.

I think the docs at the minute are simple but effective so I wouldn't worry about it as a matter of urgency.

**Comment by goriunov** [comment]
Solved :)
