### ISSUE TITLE
Error PID 1419:   TypeError: Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by amirzandi** [ClusterWS/ClusterWS#107]
### Submitting

- [ ] Bug
- [x ] Question
- [ ] Suggetion
- [ ] Other

### Details

After running server on localhost using nodemon, it keeps printing 
Error PID 1419:  
TypeError: Cannot read property '2' of undefined
on console.

what is the problem!?

**Comment by goriunov** [comment]
I need to see how to reproduce the error, without code it is very hard to track.

**Comment by amirzandi** [comment]
this is how I implemented the server: 
`const express = require('express');
const helmet = require('helmet');
const bodyParser = require('body-parser');
const moment = require('moment');
const ClusterWS = require('clusterws');

const clusterws = new ClusterWS({
  worker: worker,
  port: 4001,
  workers: 4,
  restartWorkerOnFail: true
});

function worker() {
  const server = this.server;
  const wss = this.wss;
  const app = express();

  //middlewares
  app.use(helmet());
  app.use(bodyParser.json({
    limit: '1mb'
  }));
  app.use(bodyParser.urlencoded({
    extended: true,
    limit: '1mb'
  }));

  //routes
  require('./controllers/account')(app);
  require('./controllers/game')(app);
  require('./controllers/contact')(app);
  require('./controllers/friend')(app);
  //require('./controllers/wall')(app, io);
  require('./controllers/server')(app);
  require('./controllers/leaderboard')(app);
  require('./helpers/socket/chat/main-wall').mainWall(wss);

  server.on('request', app);

  
}
`

**Comment by goriunov** [comment]
Not sure what the issue is try commenting each `require` module in the worker one by one and restart app and check if see error logs. If it stops on one of them it means u have error there. Also if it  the error is in `require('./helpers/socket/chat/main-wall').mainWall(wss);` module i may need to see some code in there.

**Comment by amirzandi** [comment]
it is still showing with remarking all of my routes: 
`const express = require('express');
const helmet = require('helmet');
const bodyParser = require('body-parser');
const moment = require('moment');
const ClusterWS = require('clusterws');

const clusterws = new ClusterWS({
  worker: worker,
  port: 4001,
  workers: 4,
  restartWorkerOnFail: true
});

function worker() {
  const server = this.server;
  const wss = this.wss;
  const app = express();

  //middlewares
  app.use(helmet());
  app.use(bodyParser.json({
    limit: '1mb'
  }));
  app.use(bodyParser.urlencoded({
    extended: true,
    limit: '1mb'
  }));

  //routes
  //require('./controllers/account')(app);
  //require('./controllers/game')(app);
  //require('./controllers/contact')(app);
  //require('./controllers/friend')(app);
  //require('./controllers/wall')(app, io);
  //require('./controllers/server')(app);
  //require('./controllers/leaderboard')(app);
  //require('./helpers/socket/chat/main-wall').mainWall(wss);

  server.on('request', app);`

**Comment by goriunov** [comment]
Oh, need to ask ios dev to check that out. May be there is something related to IOS client i will add him to this discussion.

**Comment by amirzandi** [comment]
here is the ios Code: 
`class sharedInstance {
        static let socket = WebSocket.init(url: URL.init(string: "ws://localhost:4001")!, protocols: ["chat", "superchat"])
    }`

**Comment by goriunov** [comment]
Oh ok now i get it you may need to use [ClusterWS-Swift](https://github.com/ClusterWS/ClusterWS-Client-Swift) client unfortunately ClusterWS uses special protocol which u may need to implement by yourself (and we dont have docs for that yet).

**Comment by amirzandi** [comment]
oops. this is what I was thinking about. Alright. I will let you know the result once I get it done.

**Comment by goriunov** [comment]
Sure, hope it will work alright ;)

**Comment by amirzandi** [comment]
The error has gone after I changed my swift plugin to yours. Thanks.

**Comment by goriunov** [comment]
That is nice :)
