### ISSUE TITLE
Number of clients

### ISSUE THREAD

**Issue by amirzandi** [ClusterWS/ClusterWS#108]
### Submitting

- [ ] Bug
- [x ] Question
- [ ] Suggetion
- [ ] Other

### Details

I have the following code for counting the connected clients: 

`wss.on('connection', (ws) => {
clients.push(ws);
});`

I have also 4 numbers of workers in my server configuration, it always returns 1 while I need to count the total number of clients which is: clients.length

Please save my day!

**Comment by goriunov** [comment]
Try printing `process.pid` together with  `clients.length`. Note that each worker will have it is own `clients` variable and you can not access share it without using channels.

**Comment by goriunov** [comment]
So if one suer connects to one worker your `client.length` on that worker will be 1, if another user access another worker your `client.length` on second will be 1 as well and on first will be still 1.

**Comment by amirzandi** [comment]
I have the following peace of code to handle number of connections, but the counter is not working:
`module.exports.mainWall = ((wss) => {
    var counter = 0;
    
     

    wss.setWatcher('main-wall', (message) => {
        console.log(message);
    });

    

    wss.setMiddleware('onUnsubscribe', (socket, channel) => {
        if (channel == 'main-wall') {
            counter--;
        }
        setTimeout(() => {
            wss.publish('main-wall', counter);
        });
    });
    wss.setMiddleware('onSubscribe', async(socket, channel, next) => {
        if(channel == 'main-wall') {
            counter++;
        }
        setTimeout(() => {
            wss.publish('main-wall', counter);
        }, 400);
        
        next(true);
    });


    wss.setMiddleware('verifyConnection', (info, next) => {
        console.log('verify');
        next(true);
    });

    wss.on('connection', (ws) => {
        console.log('new client connected');
    });
});`

**Comment by goriunov** [comment]
Does it print anything at all ? Can you try to print `console.log(process.pid + " " + counter)` . Also note that `onSubscribe` and `onUnsubscribe` executed only if someone connects this worker in which they listen.

**Comment by goriunov** [comment]
Oh if you will want to share date across different workers try to use `Communicate between Workers and Machines` from https://github.com/ClusterWS/ClusterWS/wiki/Middleware-Functions

**Comment by goriunov** [comment]
Ok try setting only one worker in configs. Then change your `wss.on('connection')` to:

```js
let counter = 0;
wss.on('connection', (ws) => {
    console.log('new client connected');
    counter++;
    console.log(process.pid, counter)
});
```
Try to run it and connect few times.
This one should work properly. Note that `process.pid` always prints the same number. Then set your workers param to 4 and try again and make sure you track `process.pid` some times it may be different some times the same and in places where it is the smae you will see that your counter increments.

**Comment by amirzandi** [comment]
you mean it is not possible to count connected clients while using more than 1 worker?

**Comment by goriunov** [comment]
It is but then you will need to shre date between all workers with `Communicate between Workers and Machines` from Middleware-Functions guide. Because each worker is an independent applications which uses pub sub to communicate between. That is why you can send messages to another users from other workers  only through pub sub system.

**Comment by amirzandi** [comment]
eventually, I have handled the number of connected users with following code: 

`var users = 0;

    wss.setWatcher('main-wall', (message) => {
        
    });

    wss.setMiddleware('onUnsubscribe', (socket, channel) => {
        if (channel == 'main-wall') {
            wss.publishToWorkers({
                pid: process.pid,
                action: 'unsubscribed'
            });
            setTimeout(()=>{
                wss.publish('main-wall', users);
            }, 300);
        }
    });
    wss.setMiddleware('onSubscribe', async(socket, channel, next) => {
        if(channel == 'main-wall') {
            wss.publishToWorkers({
                pid: process.pid,
                action: 'subscribed'
            });
            setTimeout(() => {
                wss.publish('main-wall', users);
            }, 300);
        }
        next(true);
    });
    wss.setMiddleware('verifyConnection', (info, next) => {
        next(true);
    });
    wss.setMiddleware('onMessageFromWorker', (data) => {
        if(data.action == 'subscribed') {
            users++;
        }
        else if(data.action == 'unsubscribed') {
            users--;
        }
    });

    wss.on('connection', (ws) => {
        console.log('new client connected');
    });`

**Comment by goriunov** [comment]
Yes that is one of the ways you can do it :)

**Comment by goriunov** [comment]
Thanks, happy that everything works ;)
