### ISSUE TITLE
Problem by adding gradle version to build.gradle of Java version

### ISSUE THREAD

**Issue by amirzandi** [ClusterWS/ClusterWS#109]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

### Details

What is the latest version or even the stablest version in order to add in my build.gradle file. I have added the following line but several commands are not available:

implementation 'com.github.ClusterWS:ClusterWS-Client-Java:1.1.1'

Please help!

**Comment by goriunov** [comment]
Could you please open this issue on [ClusterWS-Client-Java](https://github.com/ClusterWS/ClusterWS-Client-Java) Java dev should response about it :)

**Comment by amirzandi** [comment]
I already did that, no response.

**Comment by amirzandi** [comment]
Actually my colleague did do that.

**Comment by goriunov** [comment]
Java client is abit off from swift and js clients (it does not yet support version 3+ server) we will try to update it asap.

**Comment by amirzandi** [comment]
I need to implement that in my android app.

**Comment by amirzandi** [comment]
Would you please follow it up with your android department to help us on this case? We are in a middle of a project and getting closer to our deadline.
Your help would much appreciated.

**Comment by goriunov** [comment]
I think we would deploy new version in a few days. In while you can work on some other parts. (plus docs already cover most of the things properly for the library there should not be much changes for the implementation side mostly it is core changes to align with latest server version). So you can start implementing things blindly and then update to the latest version of the library to run it (not sure about changes we need yet so you may need to adjust some code later). By tomorrow evening should have more info about it. :)

**Comment by Yegorisa** [comment]
Dear @amirzandi 
I have released a new version of the Java library which the latest server implementation. The current version is 3.0.1

**Comment by goriunov** [comment]
Solved :)
