### ISSUE TITLE
Changing Ping/Pong stop my client to working

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS#110]
### Submitting

- [ ] Bug
- [ ] Question
- [ ] Suggetion
- [X] Other

I see that you have changed handling of Ping/Pong from #1/#2 to a 9 and 65 code.
My problem is that my WebSocket client send only in text mode and this is a problem with your implementation. You check is message is !== string type . My sended pong is elaborated like a message and not a pong.

**Comment by carmas123** [comment]
Solved

**Comment by goriunov** [comment]
Cool, good :) (just a note u should send it as a binary)
