### ISSUE TITLE
must I send and receive JSON messages?

### ISSUE THREAD

**Issue by gophobic** [ClusterWS/ClusterWS#112]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

Thank you for the great package, I want to use it as `ws` replacement, I have binary messages that are serialized and deserialized using protobuf3, but now, when I receive a message with `socket.on('message', callback)`, I get the error
```
Error PID 17713:  
SyntaxError: Unexpected token  in JSON at position 0
```

I really don't understand, isn't this a pure weboscket server like any other library or I have to serialze/deserilaize my messages in JSON in order to work?

**Comment by goriunov** [comment]
Hi @gophobic  unfortunately ClusterWS it self is not a replacement for  `ws` it is build on top of `uws` (which is a replacement for `ws`) to scale WebSocket across multiple machines and cpus therefore it uses specific protocol (inside) and if you want to use `protobuf3` you will need to use it inside of `EncodeDecode` option in ClusterWS and use client library in front end to communicate with Server (check documentation) unfortunately our Android library does not support `EncodeDecode` option yet but it should be added in v4.

New version of ClusterWS will be built on top of [ClusterWS-uWS](https://github.com/ClusterWS/ClusterWS-uWS) which is modified version of `uWS` so you can use it as a ws replacement.

**Comment by gophobic** [comment]
Thank you! I will surely try the other package, nice to see an active replacement of `uws` finally. Thank you!
