### ISSUE TITLE
how should i write the ping-pong code in client side

### ISSUE THREAD

**Issue by micahli** [ClusterWS/ClusterWS#124]
### Submitting

- [ ] Bug
- [X] Question
- [ ] Suggestion
- [ ] Other

**Comment by goriunov** [comment]
ClusterWS provides internal ping/pong so you don't have to worry about that stuff you can configure ping pong interval on the server (and you don't have to do any changes for clients) check [this guide](https://github.com/ClusterWS/ClusterWS/wiki/Installation-and-Configuration) at the bottom you will see option `pingInterval` which is in ms. Usually default interval is enough. I am not sure why you client is disconnecting (need more information what you are using how it works and so on).

**Comment by micahli** [comment]
The client library worked great. Thank you

**Comment by goriunov** [comment]
Cool :)
