### ISSUE TITLE
More license issues

### ISSUE THREAD

**Issue by alexhultman** [ClusterWS/ClusterWS#126]
Hello again,

License issues again;

You're using my trademarks to promote your own work -> I don't like that. Please rename your fork(s) and build your own brand.

https://tldrlegal.com/license/zlib-libpng-license-(zlib)

You're also misconstruing the origin of the software by linking to the upstream µWS yet you're using a fork. Your fork also emits error messages with references to "µWebSockets" yet.. it's not.

  2. Altered source versions must be plainly marked as such, and **must not be
     misrepresented as being the original software.**

If your **modified work** emits messages hinting of errors of the **original** like this, you're breaking license conditions.

Easiest is to either actually use the original µWS package, or stop using the same name. Must not is a pretty harsh statement and you're clearly misrepresenting my brand as is.

OpenSSL was forked and renamed LibreSSL
OpenOffice was forked renamed LibreOffice
Etc, etc

If you want to promote a fork of my software, don't drag my trademarks in. You're diluting my brand by letting users see error messages carrying my brand, which I did not produce.

µWS lives in my repo, everyting else is not and cannot carry my brand.

**Comment by goriunov** [comment]
Hi, thanks for informing. Just to clarify somethings. Current deployed version uses original software `"uws": "10.148.1"`. You can find it in `package.json` in `master` branch. `next` branch is using a fork and yes i have forgotten to change all the links and names sorry about that, I will replace things asap.

**Comment by goriunov** [comment]
Hi @alexhultman i have replaced text in README to show that it is using a fork not an original software, also i have linked it to the fork instead of uWebSocket repo, the error above it only available in current version 3.2.0 which is using original software, it will be removed with next releases. I have also changed links from `clusterws/uws` repo to link to 0.14 version of uWebSocket as you have removed uws node repo. 

About the names would you be alright if i leave 'clusterws/uws' name as it is ? When installing fork you have to do it with `npm install clusterws/uws` and i have renamed `.node` files to `clusterws_uws_version` so it will not link to your `uws` project directly.

**Comment by alexhultman** [comment]
I find it unnecessary to not make a full and proper rename/rebrand of every reference to the original so to make it very clear clause 2 is not being borderline ignored. If you read that link I sent you they list "Rename" under "Must" section which is also my interpretation and my intent with that license.

Clause 2 is one thing, but Zlib license never gave anyone trademark rights. FFmpeg was forked into libav, Node.js was forked into io.js. uWebSockets (also known as uWS) was forked into.... uWS. That's borderline trademark infringement. Esp. since "uws" was the very name used in NPM where millions of people associated that name to my code and my brand.

You don't even have any benchmarks of _your_ code but instead rely solely on established third party brands. Where are the benchmarks? I can't find them. How do you know this code _is_ fast? Oh yeah, you rely on others brands by association. If you code is really slow (which every similar project has been) that's damaging to my brand. Hence we have trademark laws.

**Comment by goriunov** [comment]
Thanks, i will rename `clusterws/uws` to something else to follow Zlib license. About the benchmark you are right i don't have it available but i am working on it they will be added eventually to `/bench` folder. I am still doing a research about proper benchmarking to make sure that i do it right.

**Comment by alexhultman** [comment]
> About the benchmark you are right **i don't have it available** but i am working on it they will be added eventually to /bench folder. I am **still doing a research about proper benchmarking** to make sure that i do it right.

This is horrible. You make such a major mental association with uWS that you even trick yourself. You really belive so hard in association, to such a delusive degree, that you don't even bother to test it in regards to what you provide.

Guess what my boy? I tested it and it has miserable performance many many times slower than the original code I provide.

Do you understand now why I don't want people to use my brand in their shit? You begin to understand why companies actually want to keep their trademarks intact?

If I had the time and money to do so, I would sue you for trademark infringement here and now. This is the equivalent to selling watered down dog shit with the logo of Coca Cola.

Please and thoroughly scrub your project of references to my project.

**Comment by alexhultman** [comment]
You need to do a lot more than that.

Currently the code has tons and tons of references that absolutely need to change. You even let the server scream out "uWebSockets" in the upgrade header. Do you understand that this is important? You **must not** (absolute prohibition) misrepresent modified versions **to any degree** as being the original.

If people see "WebSocket-Server: uWebSockets" in the browser when they use it, you don't think that **could possibly make people think it is uWebSockets**?

**That would even fool me!**

Zlib is not MIT, you cannot just hit fork and be done you need to actually go through your code and make sure you follow given conditions.

**Comment by goriunov** [comment]
Thanks, i know about performance issues and working on that. I am going to go through code and change all of the reference in the next few days.

**Comment by alexhultman** [comment]
You need to think like a lawyer:

A contract that states **must not** X means that in **any possible way imaginable**. Must not is very strict and since there is no scope of this, you need to make sure to follow this from **every perspective**;

If the server from an end user point of view shouts out "HEY I'M UWEBSOCKETS" then it doesn't matter that you have stated this is a modification in GitHub. People who haven't seen your GitHub will not know about this, thus you haven't followed conditions.

Therefore it kind of implies that you rename the entire project and go through all code and rename all references when you fork it, otherwise there will be plenty of mistakes and missed references.

Currently the server is actively shouting out that it is in fact uWebSockets. You cannot do that, you cannot keep making these mistakes over and over.

If you don't have the legal know-how to read and follow contracts and licenses then don't put yourself in such a situation.

I have changed from Zlib to Apache 2.0 upstream to make it **super clear** that people cannot do these mistakes.

**Comment by goriunov** [comment]
@alexhultman i have went through the code `@clusterws/uws` has been renamed to `@clusterws/cws` i have deprecated npm package for `@clusterws/uws` also changed the code to do not misrepresent your software including header server. 

In `next` branch of ClusterWS i have change all the description to map to the `cws` instead of `uws` (have left the note that projects is using a fork of uws to "plainly mark" altered version)

In `master` branch i am actually using original uws bindings therefore server name from http header can not be changed.

Hope you will be alright with that as it is following ZLIB conditions.
