### ISSUE TITLE
Master vs Child?

### ISSUE THREAD

**Issue by ClickSimply** [ClusterWS/ClusterWS#129]
### Submitting
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other

### Details 
Hello Dmitrii, excellent work on this project!  I'm looking at integrating this into the client/server module of my [database library](https://github.com/ClickSimply/Nano-SQL).

I have some questions regarding the Child/Master architecture when using the horizontal scaling features.

The documentation states that any server can be a master and any server can be a child, and in fact you can have multiple masters with the only requirement being that at least one master is in the cluster.

My questions:
1. What is the downside of every server being a master?  It seems to be that if a multi master setup is possible, might as well make every server a master in the setup.

2. What is a "broker" and how are they different from workers?  Looking at the scaling documentation I can see `brokersURLs` seems to connect a client to a remote master, but that doesn't explain what the local `brokerPort` property is on each config object.

Thanks so much!

**Comment by goriunov** [comment]
Hi @ClickSimply  docs need some more work (which i hope to do eventually) :) .

1. The main problems you will see with that set up is that your Masters will not be utilised fully and each server will need to hold open connections  for each master in the system so if you have 20 servers and each of them is Master then each of those 20 servers will need to connect to each other and hold open (20 * number of brokers in the current server) connections which is not optimal as you can have just 4 - 5 of them and it will/may perform much better. 

2. There are some inconsistency in naming, will need to adjust some in next release :) There are 2 main ways to scale Node.js server (can use both at the same time) one is in the single machine and second across multiple machines. So when you create workers in ClusterWS it scales your server in the current machine and to be able to communicate between different workers in your machine you need brokers (at least one). The `brokersPorts` parameter is responsible for ports which brokers will use for example if you want to change default ports:

```js
new ClusterWS({
   brokers: 2,
   // we have 2 brokers so we put two ports
   brokersPorts: [3000, 3001] 
})
```

You will need it only in case if default ports on your machine are closed or in use so you can simple overwrite default ports to your own.

Broker/Brokers is/are responsible for communication between workers so one instance of your app can send message to user from another instance.

Worker is basically a copy of the Worker function which is running in different processes (scaled)

Second way of scaling is across multiple machines and for Masters we create separate process (i will rename it eventually to Scaler) to handle communication between different machines and to be able to connect to the Master process you need to provide a `port` on your Master machine and connect from other machines through standard websocket connection url ex:
`ws://somedomain:port`.  

So 2 machines will be able to stream data between each other and user from one machine can communicate to use from another.
