### ISSUE TITLE
[Question] Scalability

### ISSUE THREAD

**Issue by fed135** [ClusterWS/ClusterWS#13]
Any plans or ideas on how this solution could be made to scale across multiple machines ?

**Comment by goriunov** [comment]
Yes i tgought about making it to scale across multipal machines, but it will be separate module as i want to have this framwork as small as possible and do not overload with unused stuff. Scaling across machins will be implemented later, for now targets are tests, documentations for all platforms, bug fixes ( as this framwork is pretty new)

**Comment by goriunov** [comment]
I have started to work with machine scaling please track in here: 
https://github.com/ClusterWS/ClusterWS/issues/25
