### ISSUE TITLE
Is it possible create different (non clone) processes?

### ISSUE THREAD

**Issue by vladikus10** [ClusterWS/ClusterWS#131]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other

### Details 

What I mean, is that currently you can create clone processes described in the `worker` function. But is it possible to spawn a completely different process? (like a background job process, which still may require the shared websocket). Maybe it is possible to somehow split the login inside the `worker` function, but how to determine which logic to use? 

With the native `cluster` module I know you can pass custom `env` variables to each process from master and use them to decide which type of process to run inside the child process.

**Comment by goriunov** [comment]
This is a flow in current design that you can not run background processes properly :( This will be improved in version 4 where you can create master function which will be executed on master process and you will be able to publish to the channels, also will be added a way to differentiate workers by id 1+ which will allow to add different logic based on the worker id. i am actually thinking i add id to the current master branch 3.2.x version (today or so)

**Comment by vladikus10** [comment]
I see, thank you for the answer. The worker id should be enough now to select the Logic for each worker.
