### ISSUE TITLE
How to determine which process current code is running in.

### ISSUE THREAD

**Issue by AlexLeung** [ClusterWS/ClusterWS#133]
### Submitting

- [ ] Bug
- [x] Question
- [x] Suggestion
- [ ] Other

### Details 

It seems that this module works by forking a new process from the main process for each worker function passed to the server.

There needs to be a way for the code to detect whether it is running within the master process or a forked process, so that the same logic isn't run multiple times. It does not make sense to try and put all the code within a worker function. That approach doesn't work well for tests, or if I'm creating a library which people should be able to import and use alongside other logic.

In my project, I was instantiating a webpack compiler after initializing the ClusterWS server, and what happened was it ended up creating 3 unique webpack compilers in separate processes.

This is basically how my project is structured:

`index.ts`
```typescript
import {Server} from './server';
console.log("about to instantiate");
new Server();
```

`server.ts`
```typescript
import config from './webpack.config';
import webpack from 'webpack';
import ClusterWS from 'clusterws';
export Server {
    constructor() {
        console.log("constructing");
        new ClusterWS({port: 8080, worker: function(){}})
        const compiler = webpack(config);
        compiler.watch({}, () => {console.log("watching")});
    }
}
```

which generates the console output of 

```
about to instantiate
constructing
about to instantiate
constructing
watching
about to instantiate
constructing
watching
✓  Master on: 8080, PID 8836
✓  Broker on: 9400, PID 7096
✓     Worker: 0, PID 13612
watching
```

So here 3 different webpack bundles are being created and emitted in the 3 separate processes of `Master`, `Broker` and `Worker`.

I really wanted to be able to use this library because it uses microWebSockets under the hood + Typescript, but given the current implementation I will need to find an alternative unfortunately.

**Comment by goriunov** [comment]
You can easily find out what is the process by using cluster module for example 
```js
import * as cluster from 'cluster';

if (cluster.isMaster) {
    // Do one wthing
} else {
    // do another 
}
```

Just for example you can use it as:
```js
import * as cluster from 'cluster';
import config from './webpack.config';
import webpack from 'webpack';
import ClusterWS from 'clusterws';

export Server {
    constructor() {
        console.log("constructing");
        new ClusterWS({port: 8080, worker: function(){}})
        if (cluster.isMaster) {
             const compiler = webpack(config);
             compiler.watch({}, () => {console.log("watching")});
        }
    }
}
```

**Comment by goriunov** [comment]
You should be able to use this logic everywhere where you need to to find if it is a master process or child :)

**Comment by AlexLeung** [comment]
Good point!
This still leaves a problem that if I'm creating a library, then I will need to inform consumers of the library they they also need to use 
```
import * as cluster from 'cluster';

if (cluster.isMaster) {
    // Do one wthing
} else {
    // do another 
}
```
so that their logic is not duplicated.
Is there any way to start the server and keep the server/worker all on the same initial process without forking?

**Comment by goriunov** [comment]
If you are creating a library then you can ask users to pass two functions to the library for example, ( `Master`, `Worker`) or two different files if needed one for Master logic and another for Worker (child). Unfortunately it is the only ways to split logic between processes even if you use raw Node.js module you will need to use this `if else` somewhere and wrap around  and then inform users on using some how by passing functions or creating files. I think all libraries which exist require you to split your logic one way or another. 

At the moment you can not run it on single worker as initial implementation was targeting scaling only (but this functionally has been discussed before and i was planning to add it)

**Comment by goriunov** [comment]
Also if you need their logic to be executed only on master you can just ask them to pass one function and exec it in `isMaster` condition (similar to what i do in ClusterWS but for Worker)

**Comment by AlexLeung** [comment]
That requirement seems a bit restrictive, but maybe I'll try it out.

Do you have any documentation on how the Workers/Brokers work: the purpose of each, how they communicate, and how they can be used for scaling? From what I'm gathering, this library allows horizontal scaling on a multicore machine, one microWebSockets server per process, with all traffic being routed through the same port.

**Comment by goriunov** [comment]
@AlexLeung sorry for a bit late response (have got lots of work lately), there is no documentation on how internally Brokers and Workers work, simply explained Broker is responsible for distribution of messages between all Workers, and worker is actually users process. All internal messaging and Pub/Sub communicate through the brokers, if you have multiple brokers then messages will be distributed between them (version 4.0.0 will have large improvements on message distribution). Brokers and workers are connected with websocket between them self. It is very simple overview of what is  happening.
