### ISSUE TITLE
PM2

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS#28]
Hi, please can you help me to use ClusterWS with my PM2 config?

```
{
  "apps": [
    {
      "name": "Server",
      "script": "bin/server.js",
      "watch": true,
      "ignore_watch": [
        "tmp",
        "log",
        "node_modules"
      ],
      "watch_options": {
        "persistent": true,
        "ignoreInitial": true
      },
      "instances" : 4,
      "exec_mode" : "cluster"
    }
  ]
}
```

This start 4 instance of my app and I'm not sure that ClusterWS can work with this config.

**Comment by goriunov** [comment]
ClusterWS works similar way by scaling on different instances with clusters, when you set {workers: 5} ClusterWS will create 5 instances of your app. PM2 can be used with ClusterWS only if you dont use property "instances" and "exec_mode" set as "fork" will look like that: 

```
{
  "apps": [
    {
      "name": "Server",
      "script": "bin/server.js",
      "watch": true,
      "ignore_watch": [
        "tmp",
        "log",
        "node_modules"
      ],
      "watch_options": {
        "persistent": true,
        "ignoreInitial": true
      },
      "exec_mode" : "fork"
    }
  ]
}
```

{workers: amount} it is exactly the same as "instances" in pm2 but with addition of socket scaling across this instances. Therefore best use of pm2 is just to restart your main process on failure, after restarting main process will automatically load all workers.

**Comment by carmas123** [comment]
Thank you I've done like that.
Regards.

**Comment by goriunov** [comment]
Solved :)
