### ISSUE TITLE
socket Events emitted like websocket from npm

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS#29]
Hi, I need to handle some events like work websocket ([https://www.npmjs.com/package/websocket](https://www.npmjs.com/package/websocket)).

With websocket I handle the event "wsServer.on('request', function(request) { })" to manage and validate the client login and origin.

There is a similar method with ClusterWS?

Please can you share what are all emitted events of SocketServer" and "Socket". Thank you.

**Comment by goriunov** [comment]
Unfortunately you can check the user which is connecting by origin only with `socket.socket.upgradeReq.headers.origin`

```js
socketServer.on('connection', function(socket){
    console.log(socket.socket.upgradeReq.headers.origin)
})
```

if you want to disconnect user in case if user is from wrong origin use `socket.disconnect()`

**Comment by goriunov** [comment]
I will add functionality to be able check origin and stop socket from connection before it has connected in next update. Thank you. :)

**Comment by goriunov** [comment]
I have added documentation at the end of this page in wiki https://github.com/ClusterWS/ClusterWS/wiki/Handle-Sockets

unfortunate i can not yet deploy this functionality to `npm` as we are still doing some updates, however if you want to use  socketServer.on('verifyConnection') you can get `index.js` file in a `dist` folder from branch `next` and import `ClusterWS` from there: 
```js
let ClusterWS = require('./index').ClusterWS 
let cws = new ClusterWS({...})
.............
```

also this update adds SSL, better TypeScript support and so on ... We will do update over all our client libraries and server at the same time soon. Plust we are moving our documentation to wiki so you can search it there :) Thank you.

**Comment by carmas123** [comment]
Thank you so much

**Comment by carmas123** [comment]
You are the best, I've tried it and work very well.
Regards

**Comment by goriunov** [comment]
Solved :)
