### ISSUE TITLE
SyntaxError: Unexpected token p in JSON at position 0

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS#30]
Hi, I got always this error when I try to send a message from my Client, how can I check when this exception was raised?

**Comment by carmas123** [comment]
Solved, my message must be a Json.

**Comment by carmas123** [comment]
Now ehn I try to send from my client a simple Json like this:

> { "message" : "this is only a test" }

I got this error
TypeError: Cannot read property '0' of undefined

**Comment by goriunov** [comment]
Javascript Client ?

**Comment by goriunov** [comment]
I have been testing it and it seems to work fine with Javascript client and server, i need to see your code to say if there any problem in the framework.

**Comment by goriunov** [comment]
Just to mention you should be able send any type of data with out any problems.

**Comment by carmas123** [comment]
My own client. I've solved with tracing into your js.
Now I dont understand the difference between "emit" and "publish".

**Comment by carmas123** [comment]
When my client send a message to server i use a json like this

{"#":["e","message","test"]}

this emit an event into server listening by socket.on("message", ...).

This is ok but into this event I don't have any reference to reply to client.

**Comment by goriunov** [comment]
//* Now I dont understand the difference between "emit" and "publish"

emit: use to communicate server <-> client.
publish: use to communicate client <-> client (allow to communicate between different workers, processes and machines), use in channels to subscribe

**Comment by goriunov** [comment]
You dont have to have reference in the message as server is holding connection in memory while user is connected, as soon as user disconnects server will remove reference.

**Comment by carmas123** [comment]
For reference I intend the reference to client and not message:
When I handle an event emitted by client

function onMessage(message, CLIENT) {
  if (message === "wow") {
    CLIENT.send("you are the best");
  }
}

CLIENT is my reference

**Comment by goriunov** [comment]
just use 
```js
socket.on("message", (data)=>{
     socket.send('any message you want')
})
```

**Comment by carmas123** [comment]
Please can you give me the ping encoded Json to implement it into my own websocket client?

**Comment by carmas123** [comment]
Done, I must send #1 when the server send to client a ping #0

**Comment by goriunov** [comment]
Solved :)
