### ISSUE TITLE
Message from Server to specified client

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS#37]
Hi, please can you explain me how can I send a message to a channel or a specified user from server?

I need to send to an user or many users a message or data when an event occur on server.

**Comment by goriunov** [comment]
For sending message to a group of users or to a specific user you should use Pub/Sub System. 
For example you want to send message to each user which are subscribed to the channel `Global`. So first you need to subscribe users, that thing you can do only from the client library as example  will use `Client-js`:

```js
// Connect socket
var cws = new ClusterWS({
    url: 'localhost',
    port: 80
})
// Listen on connection event
cws.on('connect', function(){
    let globalChannel = cws.subscribe('Global')

    // listen on messages which comes to the channel
    globalChannel.watch(function(msg){
          // print messages which you retrieve on the channel
          console.log(msg)
    })
})
```
This is example where you subscribe to the channel on `connect` event you can do it on any events you want (*BUT YOU SHOULD DO IT AFTER SOCKET IS CONNECTED*).

Ok you have done with client part, now you should send message to this channel from the server:

```js
function Worker() { 
    const httpServer = this.httpServer
    const socketServer = this.socketServer
     
    .....

    // Listen on WebSocket connection
    socketServer.on('connection', (socket) => {
        // Publish to the channel (dont forget to )
        socketServer.publish('Global', 'hello world')
    })
}

```
Make sure that when you publish event you have users connected to the channel other vise event wont fire. Also you can `socketServer.publish` from every where in the worker and on any event or action on the server. Also dont forget that Worker is scaled across  machines and the same publish event will fire on all machines so you should design server in that way that publish event only fire if it is needed.

With unique users you can do exactly the same thing but subscribe to the channel which is `unique_user_id` and then you can publish to this channel and only this user will retrieve data.

**Comment by goriunov** [comment]
This is just an example, and it mainly depends on how you want to implement your app.

**Comment by carmas123** [comment]
This is good. But I don't know why I need to ahndle the connection with a timeout:
` setTimeout(()=>socketServer.publish('Global', 'hello world'), 1000)`

The socket is not really connected when the "on('connected')" event is emitted?

**Comment by goriunov** [comment]
You don't have to use time out, it is just an example. In this example user `subscribe` to the channel on connect and we `publish` from server on connection too the problem is latency, `publish` calls before subscribe in this case (or at the same time) and that is why if in this case you wont use timeout message wont be delivered.

**Comment by goriunov** [comment]
However if you will connect two users and remove timeout, then you may notice that your first user will receive message when your second user will be connected. In that case your first user is connected and subscribed before second user is connected.

**Comment by goriunov** [comment]
You can find some details about sending messages and pub sub in this article. 

“Real Time Chat with Node.js Cluster & Websocket (ClusterWS)” https://medium.com/clusterws/clusterws-chat-with-node-js-clusters-and-websockets-cb6c1224bd79
