### ISSUE TITLE
What happens when Master instance goes down?

### ISSUE THREAD

**Issue by pritammobisoft** [ClusterWS/ClusterWS#43]
From the docs it seems that to scale a master instance is necessary. What happens when the master instance goes down? 

If this stops the cluster from working, then it can be a reliability issue. As a suggestion, I think, a better architecture will be if the servers elect a master automatically from the available instances. 

Thanks for sharing your work.

**Comment by goriunov** [comment]
If master instance goes down then while the process will go too, therefore master instance does not actually do anything except dividing incoming connection to the right workers. Basically, nothing will be able to put master instance down if you don't go inside of the library and change something (or some huge XSS attacks). At least your code won't affect master instance. However in case if you want to restart everything you can use `pm2` or `forever` to make sure that if the master goes down everything is restarted back up.

Unfortunately, it is impossible to make server select who is master and who is a worker as all workers should be running from the master.

If you are talking about scaling across machines options then it is another topic `scaleOptions` are mainly used to scale server across different machines an with this part we will work on to make it more reliable.
