### ISSUE TITLE
Upgrade from 1.4.0 to 1.5.0

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS#44]
- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

I've a problem when I try to upgrade from 1.4.0 to 1.5.0 with verifyConnection method.

This is my configuration (in 1.4.0):

```
    const verifyConnection = (info: IObject, callback: TListener) => {
        if (!originAllowed(info.origin)) callback(false); // socketServer.on('connection') won't be called

        isAuthenticatedApi(info.request, undefined, (err: Error) => {
            if (err) {
                callback(false);
                console.log(new Date() + " Rejected Unauthenticated WebSocket from origin " + info.origin + ".");
            } else
                callback(true);
        });
    };

    socketServer.on("verifyConnection", verifyConnection);
```

Now how I can convert it to work with 1.5.0?

**Comment by goriunov** [comment]
There are a couple of things which u have to look out, first is that version 1.5.0 has some breaking changes which u should change if you want it to work.

For changes check [Releases](https://github.com/ClusterWS/ClusterWS/releases)
On the client, u should check [Releases](https://github.com/ClusterWS/ClusterWS-Client-JS/releases) too 

About  `verifyConnection`, from version 1.5.0 it has the different way to implement, now it is a middleware check [Socket Documentation] (https://github.com/ClusterWS/ClusterWS/wiki/Handle-Sockets) at the bottom of the page there is info about how to use it.

**Comment by carmas123** [comment]
You are best....good good work. Thank you

**Comment by goriunov** [comment]
Solved :)
