### ISSUE TITLE
Handle worker failure ?

### ISSUE THREAD

**Issue by gobah** [ClusterWS/ClusterWS#60]
Hi there (again) !

### Submitting
- [ ] Bug
- [x] Question
- [x] Suggestion
- [ ] Other

### Details

I have read and use the recent changes and I must say that ClusterWS is really helpful and saved me a lot of time. However, I was wondering if there is a way to handle failure when a worker encounters an uncaught exception.

In our project, each worker deals with its own "instances" and shares the name of these "instances" to others workers by using new middleware functions (so all workers have a list of all available instances among all workers). I want to find a way to say to others workers that instances from the failed worker should be removed from available instances.

Does that make sense for you and do you have a solution for me?

Thank you in advance ;)

**Comment by goriunov** [comment]
Unfortunately now you have only one option and it is `restartWorkerOnFail` check `ClusterWS Available Configurations` in [Installation and Configuration](https://github.com/ClusterWS/ClusterWS/wiki/Installation-and-Configuration) Guide for more information about this options.

I will add some public available unexpected error handlers for this scenario in next version. 
Also for now you can try to wrap all inside of your `worker` function in try and catch for example: 

```js 
function Worker () {
    const wss = this.wss
    const server = this.server 
    try {
       // all your code for the server which may break
    } catch (err) {
        wss.publishToWorkers('Got an error  or some other message')
    }
}
```

This will catch all the unexpected errors in your code and you will be able to inform other workers.

**Comment by goriunov** [comment]
Reopen (will be closed as i will implement error handler function in to the core)

**Comment by goriunov** [comment]
Close issue as no proper way to catch worker error and expose functions to communicate from the same call. Developer should try to catch all error from their code
