### ISSUE TITLE
Add host option

### ISSUE THREAD

**Issue by matjazu** [ClusterWS/ClusterWS#61]
### Submitting

- [ ] Bug
- [x] Question
- [x] Suggetion
- [ ] Other

### Details

I would like to ask you if it is possible that you add `host` to ClusterWS configurations/options. For me to make use of ClusterWS, I need to pass host IP to workers http server listen method.

I prepared diff below. However, it is just off the top of my head, I could not run the ts-builder, therefore please make sure it does not break anything.

### Diff:
```
diff --git a/src/index.ts b/src/index.ts
index 6d80a4b..36f8e7e 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -13,6 +13,7 @@ export default class ClusterWS {

         const options: Options = {
             port: configurations.port || (configurations.tlsOptions ? 443 : 80),
+            host: configurations.host || null,
             worker: configurations.worker,
             workers: configurations.workers || 1,
             brokers: configurations.brokers || 1,
diff --git a/src/modules/worker/worker.ts b/src/modules/worker/worker.ts
index 73ed441..d4062f3 100644
--- a/src/modules/worker/worker.ts
+++ b/src/modules/worker/worker.ts
@@ -28,7 +28,7 @@ export class Worker {
                     this.wss.middleware.verifyConnection.call(null, info, callback) : callback(true)
         }).on('connection', (socket: WebSocket) => this.wss.emit('connection', new Socket(this, socket)))

-        this.server.listen(this.options.port, (): void => {
+        this.server.listen(this.options.port, this.options.host, (): void => {
             this.options.worker.call(this)
             process.send({ event: 'READY', pid: process.pid })
         })
diff --git a/src/utils/interfaces.ts b/src/utils/interfaces.ts
index b678225..97c5ee9 100644
--- a/src/utils/interfaces.ts
+++ b/src/utils/interfaces.ts
@@ -46,7 +46,8 @@ export interface HorizontalScaleOptions {

 export interface Configurations {
     worker: WorkerFunction
-    port?: number
+    port?: number,
+    host?: string,
     workers?: number
     brokers?: number
     useBinary?: boolean
@@ -59,7 +60,8 @@ export interface Configurations {

 export interface Options {
     worker: WorkerFunction
-    port: number
+    port: number,
+    host: string,
     workers: number
     brokers: number
     useBinary: boolean
```

Would really appreciate if `host` option can be added.

And keep up with good work :)

**Comment by goriunov** [comment]
Ok i will look into ii,  soon i am planing on releasing new version 2.1.0 which mostly  improves code style, will try to add this option on top of that release :)

**Comment by goriunov** [comment]
About tb-builder, i have updated a lot of the things in it for new 2.1.0 release u can try to install older version of ts-builder 0.6.0 , before 0.6.3 (not sure) that one should work properly with this project structure and you will be able to build everything well. As ts-builder is just for my projects i am not tracking proper version control so for example if on 0.6.1 everything works well on 0.6.2 it could break.

**Comment by matjazu** [comment]
Ok, thanks.

**Comment by goriunov** [comment]
Version 2.1.0 has been released check https://github.com/ClusterWS/ClusterWS/releases/tag/v2.1.0  for more info, i have added host options it does not break anything in test but still requires some adjusting with across servers communication.

**Comment by matjazu** [comment]
Works great, tnx.
