### ISSUE TITLE
Using ClusterWS with pm2. PIDs undefined.

### ISSUE THREAD

**Issue by Napzu** [ClusterWS/ClusterWS#91]
I am trying to use ClusterWS with pm2.

Starting server with node server.js all works fine.

But starting with pm2 start server.js and checking with pm2 monit what's going on, I get never ending log of:
server > Broker PID undefined has been restarted
server > Worker PID undefined has been restarted
server > Broker PID undefined has been restarted
server > Worker PID undefined has been restarted
server > Broker PID undefined has been restarted
server > Worker PID undefined has been restarted

**Comment by goriunov** [comment]
Thank for this issue, i am currently working on fixing it (should release new version by today). During that time just check https://github.com/ClusterWS/ClusterWS/issues/28 to know about  how to configure pm2 with ClusterWS. **This configs will not work till i make new release**

**Comment by goriunov** [comment]
Ok new version of ClusterWS is released 3.1.1 should be working fine if you follow https://github.com/ClusterWS/ClusterWS/issues/28 guide of set up,

**Comment by Napzu** [comment]
Now it works thanks you very much!
