### ISSUE TITLE
How to connect to cluster ?

### ISSUE THREAD

**Issue by Shivakishore14** [ClusterWS/ClusterWS#96]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

### Details
Version : 3.1.1
OS: Mac OS 10.13.3

I trying https://github.com/ClusterWS/ClusterWS/wiki/Horizontal-%28Machine%29-Scale this tutorial and I have the master and 2 child nodes ready as shown in the tutorial.
When i run the child nodes i get a warning like this
```
Can not connect to the Broker ws://127.0.0.1:8000/?token=undefined. System in reconnection please check your Broker and Token
```
I am not even sure if its a warning or error (some indication to that would be nice). 
Now My question is how should i connect to the cluster ?
I tried connecting to the master's port. then all the requests are handled by the master not the child nodes. Does this have something to do with the warning that i received earlier ?
And If i connect to the child's port then all the request is handled by the child (as expected).
But i would expect the child to handle the request when i request the master and the master to act as a load balancer. I might be wrong. It would be awesome to have a documentation which covered all of this. 

And for now please let me know in which node the client should connect and which port.

Thanks

**Comment by goriunov** [comment]
Ok thanks for this issue, i have release version 3.1.2 which should solve that problem (basically problem was in token which is undefined if u have not specified key should it should be  just empty string not undefined).

Basically explain, Machine Scale method u should use only if you have multiple machines however if you have only one machine with more then one cpu you better just use `workes` field as it will create as many processes (clusters) as u specify for example: 

you have Mac with 4 cores you can do like that:
```js
const clusterws = new ClusterWS({
    worker: Worker
    workers: 3 // 3 is because one of them is used for broker by default u can specify brokers amount too 
                     // if you check docs
})
```

So this configs will automatically create 3 instances of your Worker code and master process will automatically divide all incoming connection between 3 clusters like load balancer (on windows you should specify param to do so by default i think it is just filling first cluster then go to another one ONLY FOR WINDOWS)

Second example,  you have 2 machines (Macs) all connected in one network and each of them has 4 cores so here you can use Machine scale approach where you will need to run separate server on each machine:

```js
// Machine one
const clusterws = new ClusterWS({
    port: 3005
    worker: Worker
    workers: 3 
})

// Machine two
const clusterws = new ClusterWS({
    port: 3000
    worker: Worker
    workers: 3 
})
```

But now you have a problem how do this two servers communicate with each other ? How do you send message between server one and two if one user is connected to port 3000  and another one to 3005. That is where you add global broker which is basically will emit events to all servers which are connected: 

```js
// Machine one 

const clusterws = new ClusterWS({
    port: 3005
    worker: Worker
    workers: 2, // as u give one process for global broker
    horizontalScaleOptions: {
        masterOptions: {
            port:  8000
        }
   }
})
```
So this configs just creates global broker which will listen to the port 8000 connection and when second server connects to this port it will be able to communicate with server one through  **PUB SUB SYSTEM**

```
// Machine 2
const clusterws = new ClusterWS({
    port: 3000
    worker: Worker
    workers: 3,
    horizontalScaleOptions: {
        brokersUrls: ['ws://127.0.0.1:8000']
    }
})
 
```

Second server does not have global broker running so it is just connects to external one and gets all the messages from the external as well as sends messages to the external broker.

Pub sub by default sends all messages to the global brokers if they are available.

That is how you can make communication across different machines with pub sub system.

Standard `send` method does not send message to the global broker so `send` will be handled only in the server to which user is connected.


Ok now simple flow of the pub sub:

So when you publish message through pub sub it will be first send to internal broker from the server you published, then it will be passed to all workers which that server had and emitted to the clientside from each worker if there are subscribed users, then messages  will be send out to the global broker and global broker will emit that message to all other machines (which are contented to global server) and then pass to internal brokers in each of the machine and send to the workers and then go to the client side.




I know it may be abit confusing at the start but if you  just understand how it works once it should be very simple simple after that. Yes if you connect to the child port all the req will be handles by the child server (i will need to rename all the things and write proper documentation on that). Dont have much time to work on the project and docs i have got alot of things to do, but i am planing to spend more time on the project from around mid - end  of this month. Documentation requires a lot of updates.

**Comment by Shivakishore14** [comment]
Awesome thanks, Just to be clear
From client I will connect to `Machine1` port : `3005` right ?

**Comment by goriunov** [comment]
You can connect to Machine 1 (port 3005) and Machine 2 (port 3000) and whenever you publish new message on any of the Machines it will be propagated to another one.

Just to test, you can try to connect 2 clients to 2 different ports and subscribe each of them to the same channel and send publish message to that channel. Both of the clients  should get same message. You can check [THIS REPO](https://github.com/ClusterWS/ClusterWS-Tests/tree/master/ClusterWS-Machine-Scale-Tests) for some reference but it it not code example as i am using it for tests.

**Comment by goriunov** [comment]
Also you can check this thread https://github.com/ClusterWS/ClusterWS/issues/78

**Comment by Shivakishore14** [comment]
Thanks for your active response @goriunov
